const products =  [
  {
    "id": 1,
    "name": "Classic Cotton T-Shirt",
    "category": "T-Shirt",
    "price": 890,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    "rating": 4.8,
    "colors": ["Black", "White", "Gray"],
    "sizes": ["S", "M", "L", "XL"],
    "inStock": true,
    "featured": true,
    "description": "Premium cotton t-shirt with a soft, breathable fabric for everyday comfort."
  },
  {
    "id": 2,
    "name": "Slim Fit Denim Jeans",
    "category": "Jeans",
    "price": 1890,
    "image": "https://images.unsplash.com/photo-1542272604-787c3835535d",
    "rating": 4.6,
    "colors": ["Blue", "Black"],
    "sizes": ["30", "32", "34", "36"],
    "inStock": true,
    "featured": true,
    "description": "Modern slim-fit denim jeans crafted with stretch fabric for maximum comfort."
  },
  {
    "id": 3,
    "name": "Premium Casual Shirt",
    "category": "Shirt",
    "price": 1590,
    "image": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf",
    "rating": 4.7,
    "colors": ["White", "Sky Blue", "Navy"],
    "sizes": ["M", "L", "XL"],
    "inStock": true,
    "featured": false,
    "description": "A versatile casual shirt suitable for office wear and weekend outings."
  },
  {
    "id": 4,
    "name": "Oversized Hoodie",
    "category": "Hoodie",
    "price": 2290,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7",
    "rating": 4.9,
    "colors": ["Black", "Cream"],
    "sizes": ["M", "L", "XL"],
    "inStock": true,
    "featured": true,
    "description": "Soft fleece oversized hoodie designed for warmth and modern streetwear style."
  },
  {
    "id": 5,
    "name": "Traditional Cotton Panjabi",
    "category": "Panjabi",
    "price": 2490,
    "image": "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7",
    "rating": 4.8,
    "colors": ["White", "Maroon", "Navy"],
    "sizes": ["M", "L", "XL"],
    "inStock": true,
    "featured": true,
    "description": "Elegant embroidered panjabi made with premium cotton fabric."
  },
  {
    "id": 6,
    "name": "Leather Sneakers",
    "category": "Shoes",
    "price": 3290,
    "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    "rating": 4.9,
    "colors": ["White", "Black"],
    "sizes": ["40", "41", "42", "43"],
    "inStock": true,
    "featured": false,
    "description": "Lightweight leather sneakers perfect for casual everyday wear."
  },
  {
    "id": 7,
    "name": "Women's Floral Dress",
    "category": "Dress",
    "price": 2690,
    "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c",
    "rating": 4.7,
    "colors": ["Pink", "White"],
    "sizes": ["S", "M", "L"],
    "inStock": true,
    "featured": true,
    "description": "Beautiful floral dress with a comfortable fit for any occasion."
  },
  {
    "id": 8,
    "name": "Classic Polo Shirt",
    "category": "Polo",
    "price": 1290,
    "image": "https://images.unsplash.com/photo-1581655353564-df123a1eb820",
    "rating": 4.5,
    "colors": ["Black", "White", "Green"],
    "sizes": ["M", "L", "XL"],
    "inStock": true,
    "featured": false,
    "description": "Smart polo shirt with breathable fabric and a timeless design."
  },
  {
    "id": 9,
    "name": "Cargo Pants",
    "category": "Pants",
    "price": 1990,
    "image": "https://images.unsplash.com/photo-1514996937319-344454492b37",
    "rating": 4.6,
    "colors": ["Olive", "Black"],
    "sizes": ["30", "32", "34"],
    "inStock": true,
    "featured": false,
    "description": "Functional cargo pants with multiple pockets and durable fabric."
  },
  {
    "id": 10,
    "name": "Winter Jacket",
    "category": "Jacket",
    "price": 4290,
    "image": "https://images.unsplash.com/photo-1548883354-94bcfe321cbb",
    "rating": 4.9,
    "colors": ["Black", "Gray"],
    "sizes": ["M", "L", "XL"],
    "inStock": true,
    "featured": true,
    "description": "Insulated winter jacket offering warmth without compromising style."
  },
  {
    "id": 11,
    "name": "Women's Handbag",
    "category": "Accessories",
    "price": 2190,
    "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
    "rating": 4.8,
    "colors": ["Brown", "Black"],
    "sizes": ["One Size"],
    "inStock": true,
    "featured": false,
    "description": "Stylish leather handbag with spacious compartments for daily essentials."
  },
  {
    "id": 12,
    "name": "Classic Baseball Cap",
    "category": "Accessories",
    "price": 690,
    "image": "https://images.unsplash.com/photo-1521369909029-2afed882baee",
    "rating": 4.4,
    "colors": ["Black", "White", "Navy"],
    "sizes": ["Free Size"],
    "inStock": true,
    "featured": true,
    "description": "Adjustable baseball cap made with breathable cotton fabric."
  }
];
export default products;
